# Generated by Django 5.0 on 2023-12-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
