# Generated by Django 5.0 on 2023-12-15 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_photo_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='edited',
        ),
    ]
